apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology
  labels: 
    test: ng_mul
spec:
  selector:
    matchLabels:
      test: ng_mul
  replicas: 3
  template:
    metadata:
      labels:
        test: ng_mul
    spec:
      containers:
      - name: nginx
        image: nginx      
        ports:
        - containerPort: 80
      - name: multitool  
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "1180"