apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    test: ng_mul
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  - name: multitool
    port: 8080
    targetPort: 1180
    