---
all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "{{ ansible_ssh_user }}"@89.169.140.153 -i "{{ ansible_ssh_private_key_file }}""'
    become: true
    ansible_python_interpreter: /usr/bin/python3

  hosts:

    master:
      ansible_host: 10.10.10.4
      ip: 10.10.10.4
      access_ip: 10.10.10.4

    
    slave-1:
      ansible_host: 10.10.10.3
      ip: 10.10.10.3
      access_ip: 10.10.10.3
    
    slave-2:
      ansible_host: 10.10.20.3
      ip: 10.10.20.3
      access_ip: 10.10.20.3

  children:
    kube_control_plane:
      hosts:
        master:
    
    kube_node:
      hosts:
        slave-1:
        slave-2:
    
    etcd:
      hosts:
        master:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

    calico_rr:
      hosts: {}
