- name: Install jenkins
  hosts: kube_control_plane
  become: false
  gather_facts: false

  tasks:
    - name: Copy kubernetes-jenkins
      ansible.builtin.copy:
        src: '../kubernetes-jenkins/'
        dest: '~/kubernetes-jenkins/'
        mode: '0644'

    - name: Create a namespace
      ansible.builtin.command:
        cmd: 'kubectl apply -f ~/kubernetes-jenkins/namespace.yaml'

    - name: Create a service-account
      ansible.builtin.command:
        cmd: 'kubectl apply -f ~/kubernetes-jenkins/serviceAccount.yaml'

    - name: Create a volume
      ansible.builtin.command:
        cmd: 'kubectl create -f ~/kubernetes-jenkins/volume.yaml'

    - name: Apply a deployment
      ansible.builtin.command:
        cmd: 'kubectl apply -f ~/kubernetes-jenkins/deployment.yaml'

    - name: Apply a service
      ansible.builtin.command:
        cmd: 'kubectl apply -f ~/kubernetes-jenkins/service.yaml'