---
- name: Prepare to install kubespray 
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 300

  tasks:
    - name: Package install
      apt:
        name:
          - git
          - python3-pip
        state: present
        update_cache: true